import type {
  Equipment,
  MovementPattern,
  MuscleGroup,
} from '../src/generated/prisma/enums';

export interface ExerciseSeedEntry {
  name: string;
  slug: string;
  description: string;
  instructions: readonly string[];
  primaryMuscle: MuscleGroup;
  secondaryMuscles: readonly MuscleGroup[];
  equipment: Equipment;
  movementPattern: MovementPattern;
  isActive: true;
}

// Stable, system-owned slugs. Instructions are intentionally general, not a
// personalized training prescription. IDs are generated by PostgreSQL, not here.
export const exerciseCatalog: readonly ExerciseSeedEntry[] = [
  {
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    description:
      'A horizontal barbell press performed on a flat bench, primarily training the chest.',
    instructions: [
      'Lie on a flat bench with feet supported and a secure grip on the bar.',
      'Lower the bar toward the chest with control while keeping the shoulders supported.',
      'Press the bar upward and return it securely to the rack when finished.',
    ],
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'BARBELL',
    movementPattern: 'HORIZONTAL_PUSH',
    isActive: true,
  },
  {
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    description:
      'A dumbbell chest press performed with the back supported on an inclined bench.',
    instructions: [
      'Sit against an inclined bench with a dumbbell in each hand and feet supported.',
      'Press the dumbbells upward with a controlled movement.',
      'Lower them toward the sides of the upper chest within a comfortable range.',
    ],
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS', 'TRICEPS'],
    equipment: 'DUMBBELL',
    movementPattern: 'HORIZONTAL_PUSH',
    isActive: true,
  },
  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    description: 'A standing vertical barbell press focused on the shoulders.',
    instructions: [
      'Stand with a stable stance and hold the bar near shoulder height.',
      'Keep the torso steady and press the bar overhead without leaning back excessively.',
      'Lower the bar to the starting position under control.',
    ],
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['TRICEPS', 'CORE'],
    equipment: 'BARBELL',
    movementPattern: 'VERTICAL_PUSH',
    isActive: true,
  },
  {
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    description:
      'A shoulder isolation movement raising dumbbells out to the sides.',
    instructions: [
      'Hold a dumbbell at each side with a stable stance and relaxed elbows.',
      'Raise the arms out to the sides without swinging the torso.',
      'Lower the weights slowly within a comfortable range.',
    ],
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Push Up',
    slug: 'push-up',
    description:
      'A bodyweight horizontal press performed from a supported plank position.',
    instructions: [
      'Place the hands on the floor and support the body on hands and toes.',
      'Keep the trunk steady while bending the elbows to lower the chest.',
      'Push through the hands to return to the starting position with control.',
    ],
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS', 'CORE'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'HORIZONTAL_PUSH',
    isActive: true,
  },
  {
    name: 'Pull Up',
    slug: 'pull-up',
    description: 'A bodyweight vertical pull using an overhead bar.',
    instructions: [
      'Take a secure grip on a fixed overhead bar.',
      'Pull the body upward with controlled movement rather than swinging.',
      'Lower the body gradually to a comfortable extended position.',
    ],
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'FOREARMS'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'VERTICAL_PULL',
    isActive: true,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    description: 'A seated cable-based vertical pulling exercise for the back.',
    instructions: [
      'Adjust the seat and thigh support and take a secure grip on the overhead attachment.',
      'Pull the attachment toward the upper chest while keeping the torso controlled.',
      'Allow the arms to extend gradually as the attachment returns upward.',
    ],
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'FOREARMS'],
    equipment: 'CABLE',
    movementPattern: 'VERTICAL_PULL',
    isActive: true,
  },
  {
    name: 'Barbell Row',
    slug: 'barbell-row',
    description:
      'A horizontal barbell pull performed with the torso hinged forward.',
    instructions: [
      'Hold a barbell and hinge at the hips with a stable back position.',
      'Pull the bar toward the torso while keeping the trunk steady.',
      'Lower the bar under control without using a sudden body swing.',
    ],
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'SHOULDERS', 'CORE'],
    equipment: 'BARBELL',
    movementPattern: 'HORIZONTAL_PULL',
    isActive: true,
  },
  {
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    description: 'A seated horizontal cable pull focused on the back.',
    instructions: [
      'Sit with feet supported and hold the cable attachment with the torso steady.',
      'Draw the attachment toward the torso by moving the elbows backward.',
      'Extend the arms smoothly without letting the cable pull the body abruptly forward.',
    ],
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'SHOULDERS'],
    equipment: 'CABLE',
    movementPattern: 'HORIZONTAL_PULL',
    isActive: true,
  },
  {
    name: 'Back Squat',
    slug: 'back-squat',
    description:
      'A barbell squat with the bar supported across the upper back.',
    instructions: [
      'Set the bar securely across the upper back and establish a balanced stance.',
      'Bend the hips and knees to lower the body within a controlled range.',
      'Push through the feet to stand, then return the bar securely to the rack.',
    ],
    primaryMuscle: 'QUADRICEPS',
    secondaryMuscles: ['GLUTES', 'CORE'],
    equipment: 'BARBELL',
    movementPattern: 'SQUAT',
    isActive: true,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    description:
      'A machine-based leg press with the torso supported by a seat.',
    instructions: [
      'Adjust the seat and place the feet securely on the platform.',
      'Bend the knees to lower the platform while keeping the back supported.',
      'Press the platform away with control and avoid forcefully locking the knees.',
    ],
    primaryMuscle: 'QUADRICEPS',
    secondaryMuscles: ['GLUTES'],
    equipment: 'MACHINE',
    movementPattern: 'SQUAT',
    isActive: true,
  },
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    description:
      'A barbell hip-hinge movement emphasizing the hamstrings and glutes.',
    instructions: [
      'Stand holding the bar with the knees slightly bent.',
      'Move the hips backward and lower the bar close to the legs while keeping the back steady.',
      'Extend the hips to stand without leaning backward at the finish.',
    ],
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['GLUTES', 'BACK'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    isActive: true,
  },
  {
    name: 'Conventional Deadlift',
    slug: 'conventional-deadlift',
    description:
      'A barbell lift from the floor using coordinated hip and knee extension.',
    instructions: [
      'Stand near the bar, bend at the hips and knees, and take a secure grip.',
      'Keep the bar close while pushing through the feet and extending the hips and knees.',
      'Lower the bar back to the floor with a controlled hip and knee bend.',
    ],
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['HAMSTRINGS', 'QUADRICEPS', 'BACK', 'FOREARMS'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    isActive: true,
  },
  {
    name: 'Leg Extension',
    slug: 'leg-extension',
    description: 'A seated machine knee-extension exercise for the quadriceps.',
    instructions: [
      'Adjust the seat and lower-leg pad to fit the machine setup.',
      'Extend the knees smoothly while keeping the hips supported.',
      'Lower the pad with control to the starting position.',
    ],
    primaryMuscle: 'QUADRICEPS',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Leg Curl',
    slug: 'leg-curl',
    description: 'A machine knee-flexion exercise focused on the hamstrings.',
    instructions: [
      'Adjust the machine supports and leg pad to fit comfortably.',
      'Bend the knees to move the pad through a controlled range.',
      'Return gradually while keeping the hips supported.',
    ],
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['CALVES'],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    description:
      'A barbell hip-extension exercise with the upper back supported on a bench.',
    instructions: [
      'Support the upper back on a stable bench with feet planted and a padded bar across the hips.',
      'Drive through the feet to raise the hips while keeping the torso controlled.',
      'Lower the hips gradually without overextending the lower back.',
    ],
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['HAMSTRINGS'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    isActive: true,
  },
  {
    name: 'Standing Calf Raise',
    slug: 'standing-calf-raise',
    description: 'A standing machine calf raise using ankle extension.',
    instructions: [
      'Adjust the machine supports and place the feet securely on the platform.',
      'Raise the heels with control while maintaining balance.',
      'Lower the heels slowly through a comfortable range without bouncing.',
    ],
    primaryMuscle: 'CALVES',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Barbell Biceps Curl',
    slug: 'barbell-biceps-curl',
    description: 'A standing barbell elbow-flexion exercise for the biceps.',
    instructions: [
      'Hold the bar with palms facing forward and elbows near the torso.',
      'Bend the elbows to lift the bar without swinging the body.',
      'Lower the bar gradually to the starting position.',
    ],
    primaryMuscle: 'BICEPS',
    secondaryMuscles: ['FOREARMS'],
    equipment: 'BARBELL',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    description: 'A dumbbell curl performed with a neutral hand position.',
    instructions: [
      'Hold dumbbells at the sides with palms facing inward.',
      'Bend the elbows while keeping the upper arms relatively still.',
      'Lower the dumbbells smoothly without rotating into a swinging motion.',
    ],
    primaryMuscle: 'BICEPS',
    secondaryMuscles: ['FOREARMS'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Cable Triceps Pushdown',
    slug: 'cable-triceps-pushdown',
    description: 'A cable elbow-extension exercise using a high pulley.',
    instructions: [
      'Hold a high-pulley attachment with elbows near the torso.',
      'Extend the elbows to move the attachment downward without swinging the shoulders.',
      'Return the attachment upward gradually while keeping the upper arms steady.',
    ],
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Overhead Triceps Extension',
    slug: 'overhead-triceps-extension',
    description:
      'A dumbbell elbow-extension exercise with the arms positioned overhead.',
    instructions: [
      'Hold a dumbbell securely overhead with the torso steady.',
      'Bend the elbows to lower the dumbbell behind the head within a comfortable range.',
      'Extend the elbows under control without using a sudden body movement.',
    ],
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    isActive: true,
  },
  {
    name: 'Plank',
    slug: 'plank',
    description:
      'A bodyweight static hold focused on maintaining a steady trunk position.',
    instructions: [
      'Support the body on forearms and toes with elbows comfortably beneath the shoulders.',
      'Keep the trunk aligned and breathe normally while holding the position.',
      'End the hold before losing control of the body position.',
    ],
    primaryMuscle: 'CORE',
    secondaryMuscles: ['SHOULDERS'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'OTHER',
    isActive: true,
  },
  {
    name: 'Dumbbell Reverse Lunge',
    slug: 'dumbbell-reverse-lunge',
    description: 'A backward stepping lunge performed while holding dumbbells.',
    instructions: [
      'Stand with dumbbells at the sides and take a controlled step backward.',
      'Bend both knees while keeping the front foot planted and the torso steady.',
      'Push through the front foot to return to standing, then repeat on the other side.',
    ],
    primaryMuscle: 'QUADRICEPS',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS'],
    equipment: 'DUMBBELL',
    movementPattern: 'LUNGE',
    isActive: true,
  },
  {
    name: 'Farmer Carry',
    slug: 'farmer-carry',
    description:
      'A loaded walk holding dumbbells at the sides, challenging grip and trunk stability.',
    instructions: [
      'Pick up dumbbells with control and stand tall with the weights at the sides.',
      'Walk through a clear space using steady steps while keeping the torso upright.',
      'Stop and lower the weights carefully before grip or posture breaks down.',
    ],
    primaryMuscle: 'FOREARMS',
    secondaryMuscles: ['CORE', 'SHOULDERS'],
    equipment: 'DUMBBELL',
    movementPattern: 'CARRY',
    isActive: true,
  },
];
